### PR TITLE
Update message-service.js

### PR DESCRIPTION
**Pull request by ComeBurguburu**
Valid JSON format send by findAll

### CODE REVIEW

**Comment by loicortola** [comment]
Are you planning on implementing it? Or should I close the issue?

**Comment by ComeBurguburu** [comment]
You can close the issue
But we need to use try catch to detect if it's an JSONObject or a JSONArray should be always a JSONObject

**Comment by loicortola** [comment]
Please elaborate, I am not sure I understood.

**Comment by ComeBurguburu** [comment]
If the statuts is 200 the response is a JSONArray
if the statuts is 401 the response is a JSONObject

When we receive the response we don't know witch parser to choose 
parse as a JSONObject or parse as a JSONArray

The response should be always a JSONObject

**Comment by loicortola** [comment]
I don't agree.
An OK response should always have the same structure
A KO response should always have the same structure
However, relying on the same data structure to parse both states is wrong.
-> if (res.status === OK)

**Comment by ComeBurguburu** [comment]
okay got it I need to check the status code first

**Pull request closed without merging**
